[profile.default]
src     = "src"
out     = "out"
libs    = ["lib", "node_modules"]
test    = "test"
cache   = true

solc_version = "0.8.19"
optimizer    = true
optimizer_runs = 200

# Allow reading from node_modules (for OZ imports resolved via npm)
allow_paths = ["../../"]

[rpc_endpoints]
sapphire_testnet = "https://testnet.sapphire.oasis.io"
sapphire_mainnet = "https://sapphire.oasis.io"
